baseURL = "http://0x3f.org"
# languageCode = "en-us"
languageCode = "zh-cn"
title = "æ™´è€•é›¨è®€"
copyright = "Â© æ·˜æ°” 2022"
googleAnalytics = "UA-93233020-1"

# theme is the name of the hugo theme you choose,
# `hugo-theme-minima` is put here only for debuging,
# just name it whatever you're gonna handle the theme.
theme = "minima"

[pagination]
pagerSize = 15

[params]
author = "æ™´è€•é›¨è®€"
slogon = "ç¨‹åºå‘˜ï¼Œæ‹œç‹å¤§çˆ·æ•™æ•™ä¸»ã€‚"
description = ""
# iam is the beginning words of your self-introduction.
iam = ""
# The subtitle will be shown after the title of your blog site.
# e.g. "title - subtitle".
subtitle = ""
# Comment decides the comment plugin to be used on your blog site, 
# e.g. disqus, utterances, ovo.
comment = "utterances"
# timeformat, no matter what format to use, make it the second day of Jan. 2006
timeformat = "Jan 02, 2006"
# timeformat = "2006-01-02"
# switch for turning on/off lights.
switch = ["ğŸŒ", "ğŸŒš"]
# if true, date of posts will be displayed in the homepage.
displayDate = true
# if true, users can select text from your post.
selectable = true
# custom global font. notice: `globalFontFamily` won't be working
# on texts in some special positions like on titles
# globalFontFamily = 'Helvatica sans-serif'
globalFontFamily = 'LXGW WenKai'
# If set true, all your posts will use the chosen comment plugin
# except those with a `comment: false` in their front-matter
commentOnAllPosts = true

# Disqus configuration
[params.disqus]
shortname = "hugo-minima"

# Utterance configuration
# Full doc's at https://utteranc.es
# **notice**: if you're going to use utterances, you must change the 
# `repo` to your own repo address that stores comments on your site
[params.utterances]
repo = "xbot/blog-comments"
issueTerm = "pathname"

# **deprecated**
# OvO is a comment plugin written by the author of Minima.
# It is enabled when params.comment is set "ovo". You can
# find its documentation on https://github.com/ovojs/ovo.
# If you are using disqus or utterance, just ignore this field.
[params.ovo]
server = ""
placeholder = ""


# Params.social is an array containing your social network accounts,
# Each has a lowercase name, a svg formatted icon and a url to the 
# webpage of your account. They will be shown at the bottom of every
# page of your blog. 
# Be sure the svgs you use must have both its width and its height
# set 18. If you don't wanna put the svg code in this config file, 
# you can instead save them to the `data/svg.toml` file under the
# root directory of your blog. e.g. `name = '<svg>'`
[[params.social]]
name = "github"  
url = "https://github.com/xbot"
svg = ""
# [[params.social]]
# name = "linkedin"
# url = "https://linkedin/in/leonard-mivinci-63895317a"
# svg = ""
# [[params.social]]
# name = "twitter"
# url = "https://twitter.com/Leonard14733745"
# svg = ""
# [[params.social]]
# name = "telegram"
# url = "https://t.me/taoqi"
# svg = ""
[[params.social]]
name = "rss"
url = "/index.xml"
svg = ""


# Menu.main is an array that's used to decide what entries can be shown
# on the navigator of yur blog. You can use a weight to make them ordered.
[[menu.main]]
name = "ä¸»é "
url = "/"
weight = 1
[[menu.main]]
name = "æ–‡ç« "
url = "/posts"
weight = 2
[[menu.main]]
name = "æ¨™ç±¤"
url = "/tags"
weight = 3
[[menu.main]]
name = "åˆ†é¡"
url = "/categories"
weight = 4
[[menu.main]]
name = "é—œæ–¼"
url = "/about"
weight = 5


# You can classify your posts by setting taxanomies in the front matter
# e.g.
#     categories = ["dev"]
#     series = ["Building an RPC server"]
#     tags = ["hugo", "golang"]
# A little suggestion: one post belongs to one series or one category or multiple tags.
[taxonomies]
category = "categories"
tag = "tags"
series = "series"


# Make sure all the codes in a post are highlighted correctly
# so better not edit this.
[markup.highlight]
lineNos = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true
