baseURL: "http://0x3f.org"
languageCode: "zh-cn"
title: "æ™´è€•é›¨è®€"
copyright: "Â© 2007-2024 é¬¼é©¬å¦–åˆ€"
googleAnalytics: "UA-93233020-1"
theme: "minima"
defaultContentLanguage: zh-cn

pagination:
  pagerSize: 10

# languages:
# # Override language-specific configurations
#   en:
#     languageName: EN
#     weight: 1
    
#   zh-cn:
#     languageName: ç®€ä¸­
#     weight: 2
#     params:
#       greet: ä½ å¥½ :)
#       author:
#         status: ç›®å‰ä½åœ¨åœ°çƒ ğŸŒ
#         description: |
#           è¿™æ˜¯ Minima, ä¸€ä¸ªç®€æ´çš„ Hugo ä¸»é¢˜ï¼Œç§»æ¤è‡ª [Hexo Minima](https://github.com/adisaktijrs/hexo-theme-minima)ã€‚
#           æ”¯æŒæ·±è‰²æ¨¡å¼ã€å¤šè¯­è¨€ã€æ•°å­¦å…¬å¼ã€æµç¨‹å›¾ã€ä»£ç è¯­æ³•é«˜äº®ï¼Œå½“ç„¶è¿˜æœ‰åˆ†ç±»ã€æ ‡ç­¾ã€ç³»åˆ—ç­‰ç­‰ã€‚

params:
  # greet: "å–µ :)"
  greet: èƒ¡ä¸ºä¹æ¥å“‰!
  subtitle: ""
  switch: ["ğŸŒš", "ğŸŒ"]
  defaultTheme: system
  displayDate: true
  displayDescription: true
  selectable: true
  tagsTitle: æ ‡ç­¾
  categoriesTitle: åˆ†ç±»
  # commentOnAllPosts: true

  author:
    name: "æ™´è€•é›¨è®€"
    avatar: /images/avatar.png
    status: ğŸš´ ğŸˆ ğŸ“š ğŸ’» ğŸ¤”
    description: |
      ç¨‹åºå‘˜ï¼Œå–œæ¬¢çŒ«å’ŒæŠ˜å è½¦ã€‚  
      å·§è€…åŠ³è€Œæ™ºè€…å¿§ï¼Œæ— èƒ½è€…æ— æ‰€æ±‚ï¼Œé¥±é£Ÿè€Œé¨æ¸¸ï¼Œæ³›è‹¥ä¸ç³»ä¹‹èˆŸã€‚

  comment:
    enable: true
    provider: "utterances"
    disqus:
      shortname: "hugo-minima"
    utterances:
      repo: "xbot/blog-comments"
      issueTerm: "pathname"
      label: "comment"

  social:
    - name: "email"
      url: "mailto:donie.leigh@gmail.com"
    - name: "github"
      url: "https://github.com/xbot"
      svg: ""
    - name: "rss"
      url: "/index.xml"
      svg: ""

  math:
    enable: true
    provider: katex

  diagram:
    enable: true
    provider: mermaid

  search:
    enable: true
    provider: fuse
    title: æœç´¢
    placeholder: è¾“å…¥å…³é”®è¯

    fuse:
    # See also https://fusejs.io
      keys:
        - title
        - permalink
        - summary
        - content
      distance: 100
      location: 0
      threshold: 0.6
      ignoreLocation: false
      isCaseSensitive: false
      includeScore: false
      includeMatches: false
      minMatchCharLength: 1
      shouldSort: true
      findAllMatches: false

menu:
  main:
    - identifier: home
      name: ä¸»é¡µ
      weight: 1
    - identifier: posts
      name: æ–‡ç« 
      weight: 2
    - identifier: tags
      name: æ ‡ç­¾
      weight: 3
    - identifier: about
      name: å…³äº
      weight: 4
    - identifier: search
      name: ğŸ”
      weight: 5

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  highlight:
    lineNos: true
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
